"""is_got type

Revision ID: d4408107f2d5
Revises: d178b9aa7b38
Create Date: 2018-08-12 17:43:51.378372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4408107f2d5'
down_revision = 'd178b9aa7b38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coin', 'is_got')
    op.add_column('coin', sa.Column('is_got', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coin', 'is_got')
    op.add_column('coin', sa.Column('is_got', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
